name: nabeel-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "instaling python 3.12"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          python-version: "3.12"
      - run: echo "installing requirements"
      - run: pip install -r ${{ github.workspace }}/requirements.txt
      - run: echo "start running tests"
      - run: pytest
      - run: echo "test run finish!"
